apiVersion: v1
entries:
  bare:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-02-16T22:15:53.8046156Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 143a84e91d810d24aa788c02f02d320fa05ad50da5b4d471ee49f8962cec9950
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: bare
    urls:
    - bare-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - apiVersion: v1
    appVersion: 11.7.0
    created: "2021-02-16T22:15:53.8461502Z"
    deprecated: true
    description: DEPRECATED Chart for PostgreSQL, an object-relational database management
      system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 00745b88e84403be696b7514c6e8c02710d81eb6074876b0700fa28fd47a9b43
    home: https://www.postgresql.org/
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    urls:
    - charts/postgresql-8.6.4.tgz
    version: 8.6.4
generated: "2021-02-16T22:15:53.7654898Z"
